//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcaMatricula
    {
        public int Id { get; set; }
        public int GradoId { get; set; }
        public int EstudianteId { get; set; }
        public int PersonaFamiliarId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EstadoMatriculaId { get; set; }
        public string Observaciones { get; set; }
        public int Estregistro { get; set; }
        public int ContextoId { get; set; }
    
        public virtual GenPersona Acudiente { get; set; }
        public virtual GenEstudiante Estudiante { get; set; }
        public virtual TestadoMatricula Estadomatricula { get; set; }
        public virtual Tgrados Grado { get; set; }
        public virtual GenContexto GenContexto { get; set; }
    }
}
