//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenCores
    {
        public int Id { get; set; }
        public int SedeId { get; set; }
        public int JornadaId { get; set; }
        public int Estado { get; set; }
        public int Estregistro { get; set; }
    
        public virtual GenSedes GenSedes { get; set; }
        public virtual Tjornadas Tjornadas { get; set; }
    }
}
