//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenEstudiante()
        {
            this.GenFamilia = new HashSet<GenFamilia>();
            this.AcaMatricula = new HashSet<AcaMatricula>();
        }
    
        public int Id { get; set; }
        public int PersonaId { get; set; }
        public string Codigo { get; set; }
        public int Estregistro { get; set; }
        public int CapacidadExcepcionalId { get; set; }
        public int DiscapacidadId { get; set; }
    
        public virtual TcapExcepcionales CapacidadExcepcional { get; set; }
        public virtual Tdiscapacidades Discapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenFamilia> GenFamilia { get; set; }
        public virtual GenPersona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcaMatricula> AcaMatricula { get; set; }
    }
}
