//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenInstituciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenInstituciones()
        {
            this.GenNivelesAprobados = new HashSet<GenNivelesAprobados>();
            this.GenSedes = new HashSet<GenSedes>();
        }
    
        public int Id { get; set; }
        public string CodigoDane { get; set; }
        public string Nombre { get; set; }
        public string Rector { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaFundacion { get; set; }
        public int Estregistro { get; set; }
        public int Estado { get; set; }
        public int TmunicipioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenNivelesAprobados> GenNivelesAprobados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenSedes> GenSedes { get; set; }
        public virtual Tmunicipios Tmunicipios { get; set; }
    }
}
