//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenSedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenSedes()
        {
            this.GenContexto = new HashSet<GenContexto>();
        }
    
        public int Id { get; set; }
        public string CodigoDaneSede { get; set; }
        public string NombreSede { get; set; }
        public int InstitucionId { get; set; }
        public string RectorResponsable { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public int Estado { get; set; }
        public int Estregistro { get; set; }
    
        public virtual GenInstituciones GenInstituciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenContexto> GenContexto { get; set; }
    }
}
