//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlcBDEntities : DbContext
    {
        public ControlcBDEntities()
            : base("name=ControlcBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<GenInstituciones> GenInstituciones { get; set; }
        public virtual DbSet<GenNivelesAprobados> GenNivelesAprobados { get; set; }
        public virtual DbSet<GenSedes> GenSedes { get; set; }
        public virtual DbSet<SegPermisos> SegPermisos { get; set; }
        public virtual DbSet<SegRolesPermisos> SegRolesPermisos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TcapExcepcionales> TcapExcepcionales { get; set; }
        public virtual DbSet<Tcaracters> Tcaracters { get; set; }
        public virtual DbSet<Tdepartamentos> Tdepartamentos { get; set; }
        public virtual DbSet<Tdiscapacidades> Tdiscapacidades { get; set; }
        public virtual DbSet<Tdocumentos> Tdocumentos { get; set; }
        public virtual DbSet<Tespecialidades> Tespecialidades { get; set; }
        public virtual DbSet<Testratos> Testratos { get; set; }
        public virtual DbSet<Tetnias> Tetnias { get; set; }
        public virtual DbSet<Tgrados> Tgrados { get; set; }
        public virtual DbSet<Tjornadas> Tjornadas { get; set; }
        public virtual DbSet<Tmetodologias> Tmetodologias { get; set; }
        public virtual DbSet<Tmunicipios> Tmunicipios { get; set; }
        public virtual DbSet<Tniveles> Tniveles { get; set; }
        public virtual DbSet<Tpaises> Tpaises { get; set; }
        public virtual DbSet<TpVictimaConflictoes> TpVictimaConflictoes { get; set; }
        public virtual DbSet<Tsisbens> Tsisbens { get; set; }
        public virtual DbSet<GenPersona> GenPersona { get; set; }
        public virtual DbSet<AcaCalendario> AcaCalendario { get; set; }
        public virtual DbSet<AcaGrupo> AcaGrupo { get; set; }
        public virtual DbSet<GenEstudiante> GenEstudiante { get; set; }
        public virtual DbSet<GenFamilia> GenFamilia { get; set; }
        public virtual DbSet<GenUnidadOrganizacional> GenUnidadOrganizacional { get; set; }
        public virtual DbSet<SegUserContexto> SegUserContexto { get; set; }
        public virtual DbSet<TestadoMatricula> TestadoMatricula { get; set; }
        public virtual DbSet<TrelacionFamiliar> TrelacionFamiliar { get; set; }
        public virtual DbSet<AcaMatricula> AcaMatricula { get; set; }
        public virtual DbSet<GenContexto> GenContexto { get; set; }
    }
}
