//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegRolesPermisos
    {
        public int Id { get; set; }
        public int PermisoId { get; set; }
        public string RolId { get; set; }
        public int Estregistro { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual SegPermisos SegPermisos { get; set; }
    }
}
